/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author coimb
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        try {
            icon_logo =(javax.swing.JLabel)java.beans.Beans.instantiate(getClass().getClassLoader(), "view.NewJFrame_jLabel3");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        btn_entrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_comprar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_Reserve = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        fundo_branco2 = new javax.swing.JTextField();
        lbl_para_onde = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        fundo_logo = new javax.swing.JTextField();
        icon_fundoaviao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(icon_logo);
        icon_logo.setBounds(-10, 0, 100, 70);

        btn_entrar.setBackground(new java.awt.Color(31, 83, 114));
        btn_entrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_entrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_entrar.setText("ENTRAR");
        btn_entrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_entrar);
        btn_entrar.setBounds(640, 20, 120, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/award_star_silver_3.png"))); // NOI18N
        jLabel5.setText("Create by Cindy");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(680, 560, 120, 16);

        jLabel2.setText("Se você é adm clique em entrar!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 30, 180, 16);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        btn_comprar.setBackground(new java.awt.Color(31, 83, 114));
        btn_comprar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_comprar.setForeground(new java.awt.Color(255, 255, 255));
        btn_comprar.setText("Reservar");
        btn_comprar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_comprar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comprarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_comprar);
        btn_comprar.setBounds(410, 90, 180, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 70, 50, 0);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("EMBARQUE NESSA VIAGEM");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 60, 260, 20);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("LUNAR");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 90, 160, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 300, 670, 200);

        lbl_Reserve.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Reserve.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_Reserve.setForeground(new java.awt.Color(24, 77, 130));
        lbl_Reserve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Reserve.setText("Reserve sua viagem agora!");
        lbl_Reserve.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lbl_Reserve);
        lbl_Reserve.setBounds(210, 170, 320, 30);

        lbl_logo.setBackground(new java.awt.Color(0, 0, 0));
        lbl_logo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_logo.setForeground(new java.awt.Color(12, 55, 86));
        lbl_logo.setText("MOONFLY");
        getContentPane().add(lbl_logo);
        lbl_logo.setBounds(90, 10, 340, 50);

        fundo_branco2.setEditable(false);
        fundo_branco2.setBackground(new java.awt.Color(255, 255, 255));
        fundo_branco2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 153, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(102, 153, 255)));
        fundo_branco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundo_branco2ActionPerformed(evt);
            }
        });
        getContentPane().add(fundo_branco2);
        fundo_branco2.setBounds(200, 170, 350, 30);

        lbl_para_onde.setBackground(new java.awt.Color(0, 0, 0));
        lbl_para_onde.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lbl_para_onde.setForeground(new java.awt.Color(24, 77, 130));
        lbl_para_onde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_para_onde.setText("PARA ONDE VAMOS VIAJAR HOJE? ");
        lbl_para_onde.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lbl_para_onde);
        lbl_para_onde.setBounds(110, 120, 530, 50);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 153, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(102, 153, 255)));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(90, 120, 560, 40);

        fundo_logo.setEditable(false);
        fundo_logo.setBackground(new java.awt.Color(255, 255, 255));
        fundo_logo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fundo_logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundo_logoActionPerformed(evt);
            }
        });
        getContentPane().add(fundo_logo);
        fundo_logo.setBounds(0, 0, 970, 70);

        icon_fundoaviao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/_9d70a406-dd60-4983-87dd-094fff9642f1.jpg"))); // NOI18N
        getContentPane().add(icon_fundoaviao);
        icon_fundoaviao.setBounds(-120, -140, 1050, 880);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleParent(icon_fundoaviao);

        setBounds(0, 0, 818, 611);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        // TODO add your handling code here:
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
        
        
    }//GEN-LAST:event_btn_entrarActionPerformed

    private void fundo_branco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundo_branco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fundo_branco2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btn_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comprarActionPerformed
        // TODO add your handling code here:
        TelaCadastroCliente telacadastro = new TelaCadastroCliente();
        telacadastro.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_btn_comprarActionPerformed

    private void fundo_logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundo_logoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fundo_logoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_comprar;
    private javax.swing.JButton btn_entrar;
    private javax.swing.JTextField fundo_branco2;
    private javax.swing.JTextField fundo_logo;
    private javax.swing.JLabel icon_fundoaviao;
    private javax.swing.JLabel icon_logo;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbl_Reserve;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_para_onde;
    // End of variables declaration//GEN-END:variables
}
